---
baseUrl: "/"
enableRobotsTXT: true
languageCode: en-us
relativeURLs: false
title: MIT OpenCourseWare
caches:
  getjson:
    maxAge: 5m
module:
  imports:
  - path: github.com/mitodl/ocw-hugo-themes/base-theme
  - path: github.com/mitodl/ocw-hugo-themes/www
collections: []
